
export const selector = (value: string) => {
  return {
    AriaCurrent: `[aria-current="${value}"]`,
    AriaControls: `[aria-controls="${value}"]`,
    AriaControlsContains: `[aria-controls*="${value}"]`,
    AriaHidden: `[aria-hidden="${value}"]`,
    AriaLabel: `[aria-label="${value}"]`,
    AriaLabeledBy: `[aria-labelledby="${value}"]`,
    AriaLabeledByContains: `[aria-labelledby*="${value}"]`,
    AriaLabelContains: `[aria-label*="${value}"]`,
    AriaLabelNotContains: `:not([aria-label*="${value}"])`,
    AriaLabelStartsWith: `[aria-label^="${value}"]`,
    AriaLabelEndsWith: `[aria-label$="${value}"]`,
    AriaSort: `[aria-sort="${value}"]`,
    Class: `[class="${value}"]`,
    ClassWithInput: `[class="${value}"] input`,
    ClassContainsValue: `[class*="${value}"]`,
    ClassStartsWith: `[class^="${value}"]`,
    DataField: `[data-field="${value}"]`,
    DataId: `[data-id="${value}"]`,
    DataName: `[data-name="${value}"]`,
    DataTestId: `[data-testid="${value}"]`,
    DataTestIdNot: `:not([aria-testid="${value}"])`,
    DataTestIdContains: `[data-testid*="${value}"]`,
    DataTestIdEndingWith: `[data-testid$="${value}"]`,
    DataTestIdHas: `:has([data-testid="${value}"])`,
    DataTestIdHasNot: `:not(:has([data-testid="${value}"]))`,
    DataTestIdStartWith: `[data-testid^="${value}"]`,
    DataValue: `[data-value="${value}"]`,
    DataTooltip: `[data-tooltip="${value}"]`,
    Form: `[form="${value}"]`,
    HasDataTestIdAttribute: `[@data-testid="${value}"]`,
    HasNoClass: ':not([class])',
    HrefContainsValue: `[href*="${value}"]`,
    HrefEqualsValue: `[href="${value}"]`,
    Id: `[id="${value}"]`,
    IdEndingWith: `[id$="${value}"]`,
    IdStartingWith: `[id^="${value}"]`,
    IdContains: `[id*="${value}"]`,
    LabelHasIdChild: `label:has([id="${value}"])`,
    Name: `[name="${value}"]`,
    Label: `[label="${value}"]`,
    RelLink: `link[rel="${value}"]`,
    RoleValue: `[role="${value}"]`,
    Title: `[title="${value}"]`,
    Type: `[type="${value}"]`,
    Value: `[value="${value}"]`,
    DataColumn: `[data-column="${value}"]`,
    DataColumnContains: `[data-column*="${value}"]`,
    DataIdContains: `[data-id*="${value}"]`,
  };
};